image: node:14.17.0

stages:
  - lint

lint-frontend:
  stage: lint
  script:
    - cd frontend && npm install
    - node_modules/.bin/eslint .
    - node_modules/.bin/prettier -c .

lint-backend:
  stage: lint
  script:
    - cd backend && npm install
    - node_modules/.bin/eslint *.ts **/*.ts
    - node_modules/.bin/prettier -c .